# Question 1

In [1]:
import matplotlib.pylab as plt
import numpy as np

# Question 2

In [2]:
#numpy version
print(np.__version__)

#numpy configuration
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/user/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

# Question 3

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Question 4

In [4]:
Z = np.zeros((32,12))
print("%d bytes" % (Z.size * Z.itemsize))

3072 bytes


# Question 5

In [5]:
Z = np.arange(10,59)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


# Question 6

In [6]:
a = np.arange(10)
print("Original Array: ")
print(a)
print("Reverse  Array")
a = a[::-1]
print(a)

Original Array: 
[0 1 2 3 4 5 6 7 8 9]
Reverse  Array
[9 8 7 6 5 4 3 2 1 0]


# Question 7

In [7]:
a = np.arange(0,9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Question 8

In [8]:
#identity matrix

a = np.identity(3)
print('3*3 matrix:')
print(a)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 9

In [9]:
Z = np.random.random((10,11))
Zmax = Z.max()
print(Zmax)

0.985303541630716


# Question 10

In [10]:
a = np.ones((7,7))

print("Original Array: ")
print(a)

print(" 1 on the border & 0 everywhere else: ")
a[1:-1,1:-1] = 0
print(a)

Original Array: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
 1 on the border & 0 everywhere else: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# Question 11

In [11]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width = 1, mode = 'constant', constant_values = 0)
print(Z)
Z[:,[0,-1]] = 0
Z[[0,-1],:] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# Question 12

In [12]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[2. 8. 2. 0. 6. 4. 7. 1. 6. 6.]
[2. 8. 2. 0. 6. 4. 7. 1. 6. 6.]
[2. 8. 2. 0. 6. 4. 7. 1. 6. 6.]
[2 8 2 0 6 4 7 1 6 6]
[2. 8. 2. 0. 6. 4. 7. 1. 6. 6.]


# Question 13

In [13]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

#without broadcasting

Z = np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Question 14

In [14]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# Question 15

In [15]:
Z = np.random.random(10)

print("Original array:")
print(Z)

Z.sort()

print("Sorted array:")
print(Z)

Original array:
[0.46168822 0.32002572 0.80551277 0.45643639 0.65617544 0.62092052
 0.72069263 0.44372143 0.41365134 0.31987549]
Sorted array:
[0.31987549 0.32002572 0.41365134 0.44372143 0.45643639 0.46168822
 0.62092052 0.65617544 0.72069263 0.80551277]


# Question 16

In [16]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

[0.6251723  0.9109406  1.07352448 0.61860862 0.24145127 0.23192075
 0.75065062 1.23679433 1.01572935 1.19649098]
[1.18491677 1.35100968 1.15671262 0.85013008 0.97075984 1.12087294
 0.8018736  0.73854094 0.41995618 0.85375367]


# Question 17

In [17]:
Z = np.random.random(10)

print("Original array:")
print(Z)
Z[Z.argmax()] = 0
print("Maximum value replaced by 0:")
print(Z)

Original array:
[0.18557425 0.66417662 0.02999849 0.93009558 0.80709416 0.18284552
 0.48413674 0.5911701  0.87826965 0.85542664]
Maximum value replaced by 0:
[0.18557425 0.66417662 0.02999849 0.         0.80709416 0.18284552
 0.48413674 0.5911701  0.87826965 0.85542664]


# Question 18

In [18]:
Z = np.random.uniform(0, 1, 10)
print(Z)
z = 0.5
S = Z.flat[np.abs(Z - z).argmin()]
print(S)

[0.18791065 0.05790925 0.43335656 0.4607436  0.18292017 0.64792013
 0.96349092 0.33686381 0.57706916 0.46112624]
0.46112623746667236


# Question 19

In [20]:
Z = np.arange(5)[::-1]
Z = np.array([5, 4, 3, 2, 1])
n = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(n))
Z0[::n+1] = Z
print(Z0)

[5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


# Question 20

In [21]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
              
print(A * B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# Question 21

In [22]:
W = np.arange(30).reshape(6,5)
print(W)
print()

W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


# Question 22

In [26]:
from PIL import Image as img
def bbox(img):
    img = np.where(img != 0)
    rows = np.any(img, axis=1)
    cols = np.any(img, axis=0)
    r1, r2 = np.where(rows)[0][[0, -1]]
    c1, c2 = np.where(cols)[0][[0, -1]]
    return (r1,c1),(r2,c2)

img = np.array(img.open('bin_image.PNG').convert('L'))>0

print(bbox(img))

((0, 1), (1, 12965))


# Question 23

In [27]:
def moving_average(x,N = 3):
    ret = np.cumsum(x, dtype = float)
    ret[N:] = ret[N:]-ret[:-N]
    return ret[N-1:]/N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]


# Question 24

In [28]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(C)

[0 2 1 1 2 0 1]


# Question 25

In [29]:
Z = np.random.randint(0,10,50)

print("Original Array: ")
print(Z)
print("\nMost frequent value: ")
print(np.bincount(Z).argmax())

Original Array: 
[4 9 4 1 1 8 7 1 4 3 2 6 2 7 6 0 8 8 3 2 5 4 1 6 7 0 5 1 8 5 3 5 7 7 7 3 6
 0 2 1 5 1 9 4 9 7 0 3 1 6]

Most frequent value: 
1


# Question 26

In [30]:
def nlargest(a,n = 5):
    srtarr = np.argsort(a)
    sorted_arr = a[srtarr]
    result = sorted_arr[-n:]
    return result[0]

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))

9995
